package com.heavengate.commons;

public enum Errorcodes {
	
	INTERNAL_SERVER_ERROR, PASSWORD_MISMATCH, ACCOUNT_ALREADY_ACTIVE, AUTHORIZATION_NOT_ACTIVE, OPERATION_FORBIDDEN, AUTHORIZATION_NOT_FOUND,
	INCOMPLETE_REQUEST_PARAMETERS, INVALID_USER_PASSWORD, COMMUNICATION_ERROR;

}
